// Content library for Podium. Edit freely: every list is plain data.

const MODES = {
  impromptu: {
    label: "Random Topic",
    blurb: "Speak on an unexpected topic with little prep. Builds quick thinking and a clear structure.",
    framework: "PREP",
    defaultSpeak: 120,
  },
  interview: {
    label: "Interview Prep",
    blurb: "Behavioural and leadership questions. Answer with STAR and end on a measurable result.",
    framework: "STAR",
    defaultSpeak: 120,
  },
  manager: {
    label: "Manager Scenarios",
    blurb: "Role-play the hard conversations managers have: feedback, bad news, conflict, pushback.",
    framework: "SBI",
    defaultSpeak: 120,
  },
  persuade: {
    label: "Persuasion",
    blurb: "Take a side and win the room. Practise claims, evidence, objections and a clear ask.",
    framework: "MONROE",
    defaultSpeak: 120,
  },
  vocab: {
    label: "Vocabulary",
    blurb: "Get three power words. Use all of them naturally in a short talk so they stick.",
    framework: "PREP",
    defaultSpeak: 90,
  },
  research: {
    label: "Deep Research",
    blurb: "Research a topic with guided questions, then deliver a short briefing like you would to leadership.",
    framework: "SCQA",
    defaultSpeak: 180,
  },
  explain: {
    label: "Explain Simply",
    blurb: "Explain something complex so a 12-year-old gets it. The fastest test of whether you really understand it.",
    framework: "FEYNMAN",
    defaultSpeak: 90,
  },
  story: {
    label: "Storytelling",
    blurb: "Tell a short story with a hook, tension and a point. Stories are how leaders make ideas stick.",
    framework: "STORY",
    defaultSpeak: 120,
  },
};

const FRAMEWORKS = {
  PREP: {
    name: "PREP",
    use: "Any opinion or impromptu answer",
    steps: [
      ["Point", "State your main point in one sentence."],
      ["Reason", "Give the single strongest reason."],
      ["Example", "Make it concrete: a story, number or case."],
      ["Point", "Restate the point so it lands."],
    ],
  },
  STAR: {
    name: "STAR",
    use: "Behavioural interview questions",
    steps: [
      ["Situation", "Set the scene in 1-2 sentences."],
      ["Task", "What were you responsible for?"],
      ["Action", "What did YOU do? Use 'I', not 'we'. This is most of the answer."],
      ["Result", "Quantify the outcome, and say what you learned."],
    ],
  },
  SBI: {
    name: "SBI + Ask",
    use: "Giving feedback and hard conversations",
    steps: [
      ["Situation", "When and where it happened, specifically."],
      ["Behaviour", "What the person did, observable facts only."],
      ["Impact", "The effect it had on you, the team or the work."],
      ["Ask", "Invite their view, then agree on a next step together."],
    ],
  },
  MONROE: {
    name: "Monroe's Sequence",
    use: "Persuading a room to act",
    steps: [
      ["Attention", "Open with a hook: a fact, question or story."],
      ["Need", "Show the problem and why it matters to them."],
      ["Satisfaction", "Present your solution and handle the main objection."],
      ["Visualisation", "Paint the picture of the future if they act (or don't)."],
      ["Action", "Make one specific ask."],
    ],
  },
  SCQA: {
    name: "SCQA (Pyramid)",
    use: "Briefings, updates to leadership",
    steps: [
      ["Situation", "The context everyone agrees on."],
      ["Complication", "What changed or what's at risk."],
      ["Question", "The question this raises."],
      ["Answer", "Your answer first, then 3 supporting points."],
    ],
  },
  FEYNMAN: {
    name: "Feynman Technique",
    use: "Explaining complex ideas",
    steps: [
      ["One line", "Say what it is in one plain sentence."],
      ["Analogy", "Compare it to something everyday."],
      ["How it works", "Walk through it in 2-3 simple steps."],
      ["Why it matters", "Close with why anyone should care."],
    ],
  },
  STORY: {
    name: "Story Arc",
    use: "Stories and anecdotes",
    steps: [
      ["Hook", "Start in the middle of the action."],
      ["Stakes", "What could go wrong? Why did it matter?"],
      ["Turn", "The moment things changed."],
      ["Point", "The lesson, in one sentence the audience can repeat."],
    ],
  },
};

const TOPICS = {
  impromptu: [
    "Is remote work better for career growth?",
    "The most useful skill school never taught you",
    "Should every employee learn to code?",
    "What makes a great team, in your experience?",
    "Is failure overrated as a teacher?",
    "The best advice you've ever ignored",
    "Should companies have a 4-day work week?",
    "What does success look like to you in 10 years?",
    "Is social media making us better or worse communicators?",
    "The one habit that changed your life",
    "Should AI be allowed to make hiring decisions?",
    "Why do most New Year's resolutions fail?",
    "Is it better to be a specialist or a generalist?",
    "What would you change about your city?",
    "Should leaders be liked or respected?",
    "The role of luck in success",
    "Is multitasking a myth?",
    "What makes a meeting worth attending?",
    "Describe a book or film that changed your thinking",
    "Should people stay in one company for a long time?",
    "Is ambition always a good thing?",
    "How would you spend a year with no work obligations?",
    "The most underrated profession",
    "Are introverts better leaders?",
    "What does 'professionalism' really mean?",
    "Should salaries be public inside a company?",
    "What's one thing you've changed your mind about recently?",
    "Is it ever okay to break a rule at work?",
    "The future of cities in 2050",
    "Why do smart people make bad decisions?",
    "Is passion necessary to do great work?",
    "What makes someone trustworthy?",
    "Should children learn personal finance in school?",
    "The power of saying no",
    "Is it better to plan or to improvise?",
    "What would you tell your younger self about work?",
  ],
  interview: [
    "Tell me about yourself.",
    "Why do you want to move into management?",
    "Tell me about a time you led a team through a difficult deadline.",
    "Describe a conflict with a colleague and how you resolved it.",
    "Tell me about a time you failed. What did you learn?",
    "How do you handle an underperforming team member?",
    "Describe a time you influenced someone without authority.",
    "Tell me about a decision you made with incomplete information.",
    "What is your biggest weakness?",
    "Tell me about a time you disagreed with your manager.",
    "How do you prioritise when everything is urgent?",
    "Describe a time you had to deliver bad news.",
    "Tell me about your proudest professional achievement.",
    "How would your team describe you?",
    "Tell me about a time you gave difficult feedback.",
    "How do you build trust with a new team?",
    "Describe a time you drove a change that people resisted.",
    "Where do you see yourself in five years?",
    "Tell me about a time you had to learn something quickly.",
    "How do you motivate a team that's burned out?",
    "Describe a project that went off track. What did you do?",
    "Tell me about a time you took ownership of a mistake.",
    "How do you handle stakeholders with conflicting priorities?",
    "Why should we hire you over other candidates?",
    "Tell me about a time you mentored someone.",
    "How do you make decisions as a team vs alone?",
    "Describe a time you improved a process.",
    "What's your leadership style? Give an example.",
    "Tell me about a time you managed up.",
    "How do you handle pressure and stress?",
  ],
  manager: [
    "A high performer has missed three deadlines this month. Give them feedback in a 1:1.",
    "Tell your team the project they spent 3 months on has been cancelled.",
    "Two team members are in open conflict and it's affecting the team. Mediate.",
    "Your director wants a deadline you know is unrealistic. Push back respectfully.",
    "Deny a team member's promotion request and keep them motivated.",
    "Kick off your first meeting as the new manager of an existing team.",
    "A peer manager keeps taking credit for your team's work. Address it.",
    "Convince your leadership to fund an extra hire for your team.",
    "A team member tells you they're thinking of quitting. Respond.",
    "Announce a reorganisation that changes everyone's reporting line.",
    "Give positive feedback that's specific, not generic.",
    "Run a blameless post-mortem after a production outage.",
    "A client is angry about a missed delivery. Handle the call.",
    "Say no to a senior stakeholder's request without damaging the relationship.",
    "Set expectations with a new hire on their first day.",
    "Your team's engagement survey scores dropped. Address the team.",
    "Delegate an important task to someone who has never done it.",
    "Present your team's quarterly results to senior leadership.",
    "Tell a long-tenured employee their role is changing.",
    "Coach a team member who interrupts others in meetings.",
  ],
  persuade: [
    "Convince your company to adopt a 4-day work week.",
    "Argue FOR mandatory return to office. (Then try AGAINST.)",
    "Pitch a new product idea to investors in 2 minutes.",
    "Convince a sceptical team to adopt a new tool.",
    "Persuade a friend to start investing early.",
    "Argue that every company should publish salary bands.",
    "Convince your city to make public transport free.",
    "Persuade your manager to let you lead the next big project.",
    "Argue that reading fiction makes you a better leader.",
    "Convince a team to cut meetings by half.",
    "Persuade students to learn public speaking before graduating.",
    "Argue for or against AI writing assistants at work.",
    "Convince a hiring panel that soft skills matter more than hard skills.",
    "Persuade your team to give each other more direct feedback.",
    "Argue that failure should be rewarded in performance reviews.",
    "Pitch yourself for a team lead role in 90 seconds.",
    "Convince people to put their phones away during meetings.",
    "Argue that every manager should still do hands-on work.",
  ],
  explain: [
    "How does the internet work?",
    "What is inflation and why does it matter?",
    "How does a vaccine train your immune system?",
    "What is machine learning?",
    "How do credit scores work?",
    "Why is the sky blue?",
    "What is compound interest?",
    "How does a business make a profit?",
    "What is blockchain?",
    "How does GPS know where you are?",
    "What is climate change, simply?",
    "How does the stock market work?",
    "What does your job actually involve?",
    "How does electricity get to your home?",
    "What is a large language model?",
    "Why do companies do layoffs even when profitable?",
    "How does memory work in the brain?",
    "What is supply and demand?",
  ],
  story: [
    "A time you were completely out of your depth",
    "The best manager you ever had, and what they did",
    "A moment you realised you were wrong",
    "Your first day at your first job",
    "A small decision that changed everything",
    "A time someone believed in you",
    "The hardest feedback you ever received",
    "A time you helped someone without being asked",
    "A trip that didn't go as planned",
    "The moment you decided on your career",
    "A time you stood up for something",
    "A lesson you learned from a failure",
    "Someone who taught you something without trying",
    "A time a plan fell apart at the last minute",
  ],
};

// Deep research briefs: topic + guided questions + what to look up.
const RESEARCH = [
  {
    topic: "How AI is changing the role of middle managers",
    questions: ["Which manager tasks are being automated today?", "What new skills are companies asking managers for?", "What do the strongest counter-arguments say?", "What would you recommend a new manager focus on?"],
    search: ["AI impact on middle management", "Gartner future of management", "flattening organisations AI"],
  },
  {
    topic: "Why do most organisational change initiatives fail?",
    questions: ["What failure rate do studies report, and is it credible?", "What are the top 3 causes?", "What does Kotter's 8-step model say?", "One real company example of change done well"],
    search: ["Kotter leading change", "McKinsey change management success rate", "change initiative failure causes"],
  },
  {
    topic: "The science of persuasion: Cialdini's principles",
    questions: ["What are the 7 principles?", "Which two matter most in workplace settings?", "Where do they cross into manipulation?", "How would you use one in your next meeting?"],
    search: ["Cialdini Influence principles", "pre-suasion summary", "ethical persuasion at work"],
  },
  {
    topic: "Psychological safety and team performance",
    questions: ["What did Google's Project Aristotle find?", "How does Amy Edmondson define it?", "What do managers do that destroys it?", "Three behaviours that build it"],
    search: ["Project Aristotle findings", "Amy Edmondson psychological safety", "psychological safety manager behaviours"],
  },
  {
    topic: "Remote vs office work: what does the data say about productivity?",
    questions: ["What do the large studies conclude?", "Where does remote work underperform?", "What's the effect on junior employees?", "What policy would you recommend and why?"],
    search: ["Nick Bloom remote work study", "hybrid work productivity research", "remote work mentoring junior staff"],
  },
  {
    topic: "The four-day work week trials",
    questions: ["Where were the major trials run?", "What happened to productivity and wellbeing?", "Which industries does it not suit?", "Would it work in your company?"],
    search: ["4 day week UK pilot results", "Iceland four day week trial", "four day week criticisms"],
  },
  {
    topic: "How great leaders run effective 1:1 meetings",
    questions: ["What's the purpose of a 1:1?", "What do 'Radical Candor' and 'The Manager's Path' recommend?", "Common mistakes new managers make", "Design your ideal 1:1 agenda"],
    search: ["Radical Candor 1:1", "effective one on one meetings manager", "Andy Grove High Output Management 1:1"],
  },
  {
    topic: "The economics of India's growing tech sector",
    questions: ["How big is the sector and how fast is it growing?", "What are the main drivers?", "Biggest risks in the next 5 years", "What does this mean for your career?"],
    search: ["NASSCOM industry report", "India GCC global capability centres growth", "India IT sector AI risk"],
  },
  {
    topic: "Why do people resist feedback, and how do you deliver it so it lands?",
    questions: ["What does research say about feedback and the brain's threat response?", "What is the SBI model?", "Praise-to-criticism ratios: myth or real?", "Script one piece of feedback you need to give"],
    search: ["SCARF model David Rock", "SBI feedback model CCL", "Thanks for the Feedback Stone Heen"],
  },
  {
    topic: "What makes a speech memorable? Study one great speech",
    questions: ["Pick a speech (e.g. Steve Jobs Stanford 2005). What structure does it use?", "Which rhetorical devices appear?", "How does it open and close?", "What one technique will you borrow?"],
    search: ["Steve Jobs Stanford speech analysis", "rhetorical devices famous speeches", "Nancy Duarte resonate speech structure"],
  },
  {
    topic: "Decision-making under uncertainty for leaders",
    questions: ["What is a 'one-way door' vs 'two-way door' decision?", "What cognitive biases affect leaders most?", "How do pre-mortems work?", "Apply it to a decision you face"],
    search: ["Bezos one-way two-way door", "pre-mortem Gary Klein", "Thinking Fast and Slow leadership biases"],
  },
  {
    topic: "The rise of electric vehicles: winners and losers",
    questions: ["Current global adoption numbers", "What's holding adoption back?", "Who wins and who loses economically?", "Your prediction for 2035"],
    search: ["IEA global EV outlook", "EV adoption barriers", "EV impact on oil and auto jobs"],
  },
];

// Power vocabulary for managers and persuasive speakers.
const VOCAB = [
  ["articulate", "adj./verb", "Expressing ideas clearly; to express clearly", "She articulated the team's vision in two sentences."],
  ["candid", "adj.", "Truthful and straightforward; frank", "I'd like to be candid about where the project stands."],
  ["cogent", "adj.", "Clear, logical and convincing", "He made a cogent case for the extra budget."],
  ["galvanize", "verb", "Shock or excite someone into taking action", "The customer story galvanized the team."],
  ["mitigate", "verb", "Make something less severe", "We added a review step to mitigate the risk."],
  ["substantiate", "verb", "Provide evidence to support a claim", "Can we substantiate that with data?"],
  ["delineate", "verb", "Describe or define precisely", "Let me delineate who owns which part."],
  ["consensus", "noun", "General agreement among a group", "We reached consensus after one meeting."],
  ["catalyst", "noun", "Something that causes important change", "The outage was a catalyst for better monitoring."],
  ["compelling", "adj.", "Evoking interest or attention in a powerful way", "That's a compelling reason to act now."],
  ["ambiguity", "noun", "Uncertainty; openness to more than one meaning", "Good managers are comfortable with ambiguity."],
  ["trajectory", "noun", "The path or direction of development", "Our growth trajectory is strong."],
  ["synthesize", "verb", "Combine ideas into a coherent whole", "Let me synthesize what I've heard so far."],
  ["advocate", "verb/noun", "Publicly support; a supporter", "I'll advocate for your promotion."],
  ["constructive", "adj.", "Serving a useful purpose; helpful", "Thank you for the constructive feedback."],
  ["decisive", "adj.", "Able to make decisions quickly and effectively", "In a crisis, the team needs a decisive leader."],
  ["scrutinize", "verb", "Examine closely and thoroughly", "Finance will scrutinize every line of the budget."],
  ["contingency", "noun", "A plan for a possible future event", "What's our contingency if the vendor fails?"],
  ["feasible", "adj.", "Possible and practical to do", "Is a March launch feasible?"],
  ["salient", "adj.", "Most noticeable or important", "The salient point is that costs doubled."],
  ["tenable", "adj.", "Able to be defended or maintained", "The current workload isn't tenable."],
  ["unequivocal", "adj.", "Leaving no doubt; unambiguous", "The answer from customers was unequivocal."],
  ["judicious", "adj.", "Having good judgement; sensible", "We need to be judicious with the remaining budget."],
  ["expedite", "verb", "Make something happen faster", "Can we expedite the approval?"],
  ["foster", "verb", "Encourage the development of", "I want to foster a culture of open feedback."],
  ["bolster", "verb", "Support or strengthen", "These numbers bolster our argument."],
  ["underscore", "verb", "Emphasise; draw attention to", "This incident underscores the need for testing."],
  ["holistic", "adj.", "Considering the whole rather than parts", "We need a holistic view of the customer journey."],
  ["discern", "verb", "Perceive or recognise something not obvious", "It's hard to discern a pattern yet."],
  ["convey", "verb", "Communicate or make known", "The chart conveys the trend instantly."],
  ["rationale", "noun", "The reasons behind a decision", "Let me walk you through the rationale."],
  ["juxtapose", "verb", "Place side by side for contrast", "Juxtapose last year's numbers with this year's."],
  ["pivotal", "adj.", "Of crucial importance", "This quarter is pivotal for the team."],
  ["prudent", "adj.", "Acting with care for the future", "It would be prudent to wait for the data."],
  ["rapport", "noun", "A close, harmonious relationship", "Build rapport before you ask for something."],
  ["tangible", "adj.", "Real, concrete, measurable", "We need tangible results by Q3."],
  ["meticulous", "adj.", "Showing great attention to detail", "Her documentation is meticulous."],
  ["proactive", "adj.", "Acting in advance rather than reacting", "Be proactive about flagging risks."],
  ["reconcile", "verb", "Make two things compatible; restore harmony", "How do we reconcile speed with quality?"],
  ["elucidate", "verb", "Make something clear; explain", "Could you elucidate the second point?"],
  ["pertinent", "adj.", "Relevant to the matter at hand", "That's a pertinent question."],
  ["cohesive", "adj.", "Forming a united whole", "We're a more cohesive team now."],
  ["impetus", "noun", "The force that makes something happen", "The new law gave impetus to the project."],
  ["conducive", "adj.", "Making a certain outcome likely", "Open offices aren't always conducive to focus."],
  ["empathetic", "adj.", "Showing understanding of others' feelings", "An empathetic response calms the room."],
  ["resilient", "adj.", "Able to recover quickly from setbacks", "The team proved resilient after the setback."],
  ["accountability", "noun", "Responsibility for one's actions and outcomes", "Accountability starts with me."],
  ["alignment", "noun", "Agreement on goals and direction", "Let's get alignment before we build."],
  ["nuance", "noun", "A subtle difference in meaning", "There's nuance here we shouldn't ignore."],
  ["pragmatic", "adj.", "Dealing with things sensibly and realistically", "Let's take a pragmatic approach."],
  ["leverage", "verb", "Use something to maximum advantage", "We can leverage our existing customers."],
  ["concise", "adj.", "Giving a lot of information clearly in few words", "Keep the update concise."],
  ["paradigm", "noun", "A typical model or pattern of thinking", "Remote work shifted the paradigm."],
  ["incremental", "adj.", "Increasing in small steps", "We'll make incremental improvements."],
  ["imperative", "noun/adj.", "Of vital importance; crucial", "It's imperative we fix this before launch."],
  ["discerning", "adj.", "Having good judgement", "Our customers are discerning."],
  ["inherent", "adj.", "Existing as a natural part of something", "There's an inherent risk in any launch."],
  ["candour", "noun", "The quality of being open and honest", "I appreciate your candour."],
  ["provenance", "noun", "The origin or source of something", "What's the provenance of this data?"],
  ["corroborate", "verb", "Confirm or give support to a statement", "Two other teams corroborate this finding."],
];

const WARMUPS = [
  { title: "No-filler minute", body: "Talk for 60 seconds about your morning. Every time you want to say 'um', 'like' or 'so', pause silently instead." },
  { title: "Tongue twister", body: "Say three times, faster each time: 'Red leather, yellow leather. Unique New York. Toy boat.'" },
  { title: "Rule of three", body: "Describe your job using exactly three points. 'There are three parts to what I do: first... second... third...'" },
  { title: "One-sentence summary", body: "Summarise the last book, film or article you consumed in one sentence. Then in ten words. Then in five." },
  { title: "Pause power", body: "Read a paragraph aloud and add a full 2-second pause after every sentence. Notice how much more confident it sounds." },
  { title: "Vocal variety", body: "Say 'I never said she stole the money' seven times, stressing a different word each time. Hear the meaning change." },
  { title: "Opening hook", body: "Write three different first sentences for the same talk: a question, a surprising fact, and a story. Say each aloud." },
  { title: "Breathing reset", body: "Breathe in for 4 counts, hold for 4, out for 6. Repeat 4 times. Slower breath means slower, steadier speech." },
  { title: "Answer first", body: "Answer: 'How was your week?' Start with your one-line answer, then add one detail. No preamble." },
  { title: "Replace a hedge", body: "Say five sentences starting with 'I think...', then repeat them starting with 'I recommend...' or 'My view is...'." },
];

// Word lists used by the analyser.
const FILLERS = ["um", "umm", "uh", "uhh", "er", "erm", "ah", "hmm", "like", "you know", "i mean", "basically", "actually", "literally", "so yeah", "kind of", "sort of", "right", "okay so", "anyway", "whatever", "stuff like that", "and stuff", "or something"];
const HEDGES = ["i think", "i guess", "i feel like", "maybe", "perhaps", "probably", "just", "i'm not sure", "i don't know", "kind of", "sort of", "a little bit", "hopefully", "might", "i suppose", "if that makes sense", "does that make sense", "sorry", "i'm no expert", "i could be wrong", "try to"];
const POWER = ["i recommend", "i propose", "i will", "we will", "i decided", "i led", "i owned", "i delivered", "clearly", "the key", "most importantly", "the evidence", "the data shows", "i'm confident", "i believe", "my recommendation", "here's why", "the result", "we achieved", "i drove", "i built", "i initiated", "imagine", "the bottom line"];
const SIGNPOSTS = ["first", "firstly", "second", "secondly", "third", "thirdly", "finally", "next", "then", "however", "on the other hand", "for example", "for instance", "in summary", "to summarise", "to summarize", "in conclusion", "to conclude", "the reason", "because", "therefore", "as a result", "that's why", "let me explain", "in short", "to sum up", "the first", "the second", "the third", "another", "lastly", "most importantly", "on top of that", "in addition"];
const CLOSERS = ["in summary", "to summarise", "to summarize", "in conclusion", "to conclude", "to sum up", "in short", "so my point is", "the bottom line", "that's why", "so the key takeaway", "the takeaway", "so i recommend", "my ask is", "let's", "i'd ask you to"];
const STORY_MARKERS = ["for example", "for instance", "imagine", "picture this", "i remember", "one time", "last year", "a few years ago", "when i was", "there was a time", "let me tell you", "story", "at my last", "in my previous", "in my last role", "at my current"];
const STAR_MARKERS = {
  situation: ["situation", "context", "at the time", "when i was", "we were", "the problem was", "background", "in my previous", "at my last", "the company", "the team was"],
  task: ["my role", "my task", "i was responsible", "my responsibility", "i needed to", "i had to", "the goal was", "the objective", "i was asked", "my job was", "the challenge"],
  action: ["i decided", "i started", "i created", "i led", "i organised", "i organized", "i set up", "i spoke", "i proposed", "i built", "i scheduled", "i worked with", "i analysed", "i analyzed", "first i", "then i", "so i", "i made", "i reached out", "i introduced"],
  result: ["as a result", "the result", "resulted in", "we achieved", "increased", "reduced", "improved", "saved", "delivered", "percent", "%", "outcome", "in the end", "eventually", "i learned", "we hit", "lesson"],
};
const STOPWORDS = new Set("a an the and or but if then so to of in on at for with by from up about into over after is are was were be been being am i me my we our you your he she it they them their this that these those there here what which who whom when where why how not no do does did have has had will would can could should may might must just very really also as than too more most some any all each other such only own same both few again further once its it's i'm we're you're they're that's what's don't didn't can't won't isn't wasn't aren't let's let us him her his hers yeah ok okay".split(" "));
